# Generated by Django 6.0.3 on 2026-03-19 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detector', '0003_alter_phishingurl_id_alter_scanresult_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scanresult',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='scanresult',
            name='email_sender',
        ),
        migrations.RemoveField(
            model_name='scanresult',
            name='email_text',
        ),
        migrations.RemoveField(
            model_name='scanresult',
            name='result',
        ),
        migrations.RemoveField(
            model_name='scanresult',
            name='risk_score',
        ),
        migrations.AddField(
            model_name='scanresult',
            name='count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='scanresult',
            name='status',
            field=models.CharField(default='safe', max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='scanresult',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
